### ISSUE TITLE
Remote Script Installation

### ISSUE THREAD

**Issue by DanielKosmo** [KBLiveSolutions/open.control-remote_script#2]
Hi,

I'm using Live11 and Live10 (because of CLYPHX).
I followed the installation instructions. 
'open control' appears as a remote control in Live 11 but NOT in Live 10. It does appear as Midi I/O for both versions.
It's the same file path for the User Library. 

Any hints?

Greetings from Belgium,

Daniel
![Live10](https://user-images.githubusercontent.com/98474847/151194954-10c80fec-7a08-4e7c-a3cf-f6b60f511212.png)
![Live11](https://user-images.githubusercontent.com/98474847/151194993-53332301-e7d7-4e90-b47e-379292e6008e.png)

**Comment by KBLiveSolutions** [comment]
I have fixed the Live 10 compatibility issue, please download the the remote script .zip and go through the installation process again, you should see the script appear in your Control Surface list (don't forget to relaunch Live).

Be aware that some Live 11 features (Variations etc) won't be available on L10 and may cause some issues.

Please report any problems in the [Troubleshooting section](https://github.com/KBLiveSolutions/open.control/discussions/categories/troubleshooting) of the [Discussions](https://github.com/KBLiveSolutions/open.control/discussions).
